// <auto-generated />
using System;
using GLOWAPI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GLOWAPI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260524005716_RefactorSessaoAutenticacaoGlowToken")]
    partial class RefactorSessaoAutenticacaoGlowToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CanceladoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EstabelecimentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ProfissionalAutonomoId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioClienteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId");

                    b.HasIndex("ProfissionalAutonomoId");

                    b.HasIndex("UsuarioClienteId");

                    b.ToTable("Agendamentos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Agendamentos_Titular", "((\"EstabelecimentoId\" IS NOT NULL AND \"ProfissionalAutonomoId\" IS NULL) OR (\"EstabelecimentoId\" IS NULL AND \"ProfissionalAutonomoId\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.AgendamentoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgendamentoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProfissionalId")
                        .HasColumnType("integer");

                    b.Property<int?>("RepassadoDeProfissionalId")
                        .HasColumnType("integer");

                    b.Property<int>("ServicoId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.HasIndex("ProfissionalId");

                    b.HasIndex("RepassadoDeProfissionalId");

                    b.HasIndex("ServicoId");

                    b.ToTable("AgendamentoItens", null, t =>
                        {
                            t.HasCheckConstraint("CK_AgendamentoItens_Horario", "\"Inicio\" < \"Fim\"");
                        });
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Assinatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CanceladoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EstabelecimentoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Fim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GatewayCustomerId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("GatewaySubscriptionId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlanoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProfissionalAutonomoId")
                        .HasColumnType("integer");

                    b.Property<bool>("RenovacaoAutomatica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("UltimoPagamentoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId");

                    b.HasIndex("PlanoId");

                    b.HasIndex("ProfissionalAutonomoId");

                    b.ToTable("Assinaturas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Assinaturas_Titular", "((\"EstabelecimentoId\" IS NOT NULL AND \"ProfissionalAutonomoId\" IS NULL) OR (\"EstabelecimentoId\" IS NULL AND \"ProfissionalAutonomoId\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Caixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EstabelecimentoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProfissionalAutonomoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SaldoDisponivel")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("SaldoRetido")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("SaldoTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId")
                        .IsUnique();

                    b.HasIndex("ProfissionalAutonomoId")
                        .IsUnique();

                    b.ToTable("Caixas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Caixas_Titular", "((\"EstabelecimentoId\" IS NOT NULL AND \"ProfissionalAutonomoId\" IS NULL) OR (\"EstabelecimentoId\" IS NULL AND \"ProfissionalAutonomoId\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.ComissaoProfissional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FimVigencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InicioVigencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Percentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("ProfissionalEstabelecimentoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoComissao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ValorFixo")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProfissionalEstabelecimentoId");

                    b.ToTable("ComissoesProfissional", (string)null);
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EstabelecimentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ProfissionalAutonomoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId")
                        .IsUnique();

                    b.HasIndex("ProfissionalAutonomoId")
                        .IsUnique();

                    b.ToTable("Enderecos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Enderecos_Titular", "((\"EstabelecimentoId\" IS NOT NULL AND \"ProfissionalAutonomoId\" IS NULL) OR (\"EstabelecimentoId\" IS NULL AND \"ProfissionalAutonomoId\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Estabelecimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("PublicGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PublicGuid")
                        .IsUnique();

                    b.ToTable("Estabelecimentos", (string)null);
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.EstabelecimentoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstabelecimentoId")
                        .HasColumnType("integer");

                    b.Property<string>("RoleNoEstabelecimento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EstabelecimentoId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("EstabelecimentoUsuarios", (string)null);
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.HorarioAtendimentoProfissional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<int?>("EstabelecimentoId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<int>("ProfissionalId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId");

                    b.HasIndex("ProfissionalId", "EstabelecimentoId", "DiaSemana", "HoraInicio", "HoraFim")
                        .IsUnique();

                    b.ToTable("HorariosAtendimentoProfissional", null, t =>
                        {
                            t.HasCheckConstraint("CK_HorariosAtendimentoProfissional_Horario", "\"HoraInicio\" < \"HoraFim\"");
                        });
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.HorarioFuncionamentoEstabelecimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<int>("EstabelecimentoId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId", "DiaSemana", "HoraInicio", "HoraFim")
                        .IsUnique();

                    b.ToTable("HorariosFuncionamentoEstabelecimento", null, t =>
                        {
                            t.HasCheckConstraint("CK_HorariosFuncionamentoEstabelecimento_Horario", "\"HoraInicio\" < \"HoraFim\"");
                        });
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.LancamentoCaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgendamentoId")
                        .HasColumnType("integer");

                    b.Property<int>("CaixaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PagamentoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProfissionalId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.HasIndex("CaixaId");

                    b.HasIndex("PagamentoId");

                    b.HasIndex("ProfissionalId");

                    b.ToTable("LancamentosCaixa", (string)null);
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.LogAutenticacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detalhes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Evento");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogsAutenticacao", (string)null);
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.MetaProfissional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FimPeriodo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InicioPeriodo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProfissionalEstabelecimentoId")
                        .HasColumnType("integer");

                    b.Property<int?>("QuantidadeAtendimentos")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoMeta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ValorFaturamento")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProfissionalEstabelecimentoId");

                    b.HasIndex("Status");

                    b.ToTable("MetasProfissional", (string)null);
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgendamentoId")
                        .HasColumnType("integer");

                    b.Property<int?>("AssinaturaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GatewayPaymentId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime?>("PagoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.HasIndex("AssinaturaId");

                    b.HasIndex("GatewayPaymentId");

                    b.ToTable("Pagamentos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pagamentos_Origem", "((\"AgendamentoId\" IS NOT NULL AND \"AssinaturaId\" IS NULL) OR (\"AgendamentoId\" IS NULL AND \"AssinaturaId\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Plano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("LimiteAgendamentos")
                        .HasColumnType("integer");

                    b.Property<int?>("LimiteProfissionais")
                        .HasColumnType("integer");

                    b.Property<int?>("LimiteServicos")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Planos", (string)null);
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Profissional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Biografia")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomePublico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("PublicGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoProfissional")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PublicGuid")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Profissionais", (string)null);
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.ProfissionalEstabelecimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstabelecimentoId")
                        .HasColumnType("integer");

                    b.Property<bool>("PodeReceberAgendamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ProfissionalId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId");

                    b.HasIndex("ProfissionalId");

                    b.ToTable("ProfissionalEstabelecimentos", (string)null);
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.ProfissionalServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer");

                    b.Property<decimal>("Preco")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("ProfissionalId")
                        .HasColumnType("integer");

                    b.Property<int>("ServicoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServicoId");

                    b.HasIndex("ProfissionalId", "ServicoId")
                        .IsUnique();

                    b.ToTable("ProfissionalServicos", (string)null);
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer");

                    b.Property<int?>("EstabelecimentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("PrecoBase")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int?>("ProfissionalAutonomoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId");

                    b.HasIndex("ProfissionalAutonomoId");

                    b.ToTable("Servicos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Servicos_Titular", "((\"EstabelecimentoId\" IS NOT NULL AND \"ProfissionalAutonomoId\" IS NULL) OR (\"EstabelecimentoId\" IS NULL AND \"ProfissionalAutonomoId\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.SessaoAutenticacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccessTokenExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AccessTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("LoginEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UltimaRenovacaoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccessTokenHash");

                    b.HasIndex("ExpiraEm");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("SessoesAutenticacao", (string)null);
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("BloqueadoAte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Tentativas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.WebhookPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErroProcessamento")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Processado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Gateway", "EventId")
                        .IsUnique();

                    b.ToTable("WebhookPagamentos", (string)null);
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("GLOWAPI.Domain.Entities.Estabelecimento", "Estabelecimento")
                        .WithMany("Agendamentos")
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GLOWAPI.Domain.Entities.Profissional", "ProfissionalAutonomo")
                        .WithMany("AgendamentosAutonomo")
                        .HasForeignKey("ProfissionalAutonomoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GLOWAPI.Domain.Entities.Usuario", "UsuarioCliente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("UsuarioClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estabelecimento");

                    b.Navigation("ProfissionalAutonomo");

                    b.Navigation("UsuarioCliente");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.AgendamentoItem", b =>
                {
                    b.HasOne("GLOWAPI.Domain.Entities.Agendamento", "Agendamento")
                        .WithMany("Itens")
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GLOWAPI.Domain.Entities.Profissional", "Profissional")
                        .WithMany("AgendamentoItens")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GLOWAPI.Domain.Entities.Profissional", "RepassadoDeProfissional")
                        .WithMany("AgendamentoItensRepassados")
                        .HasForeignKey("RepassadoDeProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GLOWAPI.Domain.Entities.Servico", "Servico")
                        .WithMany("AgendamentoItens")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agendamento");

                    b.Navigation("Profissional");

                    b.Navigation("RepassadoDeProfissional");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Assinatura", b =>
                {
                    b.HasOne("GLOWAPI.Domain.Entities.Estabelecimento", "Estabelecimento")
                        .WithMany("Assinaturas")
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GLOWAPI.Domain.Entities.Plano", "Plano")
                        .WithMany("Assinaturas")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GLOWAPI.Domain.Entities.Profissional", "ProfissionalAutonomo")
                        .WithMany("AssinaturasAutonomo")
                        .HasForeignKey("ProfissionalAutonomoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Estabelecimento");

                    b.Navigation("Plano");

                    b.Navigation("ProfissionalAutonomo");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Caixa", b =>
                {
                    b.HasOne("GLOWAPI.Domain.Entities.Estabelecimento", "Estabelecimento")
                        .WithOne("Caixa")
                        .HasForeignKey("GLOWAPI.Domain.Entities.Caixa", "EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GLOWAPI.Domain.Entities.Profissional", "ProfissionalAutonomo")
                        .WithOne("Caixa")
                        .HasForeignKey("GLOWAPI.Domain.Entities.Caixa", "ProfissionalAutonomoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Estabelecimento");

                    b.Navigation("ProfissionalAutonomo");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.ComissaoProfissional", b =>
                {
                    b.HasOne("GLOWAPI.Domain.Entities.ProfissionalEstabelecimento", "ProfissionalEstabelecimento")
                        .WithMany("Comissoes")
                        .HasForeignKey("ProfissionalEstabelecimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProfissionalEstabelecimento");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("GLOWAPI.Domain.Entities.Estabelecimento", "Estabelecimento")
                        .WithOne("Endereco")
                        .HasForeignKey("GLOWAPI.Domain.Entities.Endereco", "EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GLOWAPI.Domain.Entities.Profissional", "ProfissionalAutonomo")
                        .WithOne("Endereco")
                        .HasForeignKey("GLOWAPI.Domain.Entities.Endereco", "ProfissionalAutonomoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Estabelecimento");

                    b.Navigation("ProfissionalAutonomo");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.EstabelecimentoUsuario", b =>
                {
                    b.HasOne("GLOWAPI.Domain.Entities.Estabelecimento", "Estabelecimento")
                        .WithMany("Usuarios")
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GLOWAPI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Estabelecimentos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estabelecimento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.HorarioAtendimentoProfissional", b =>
                {
                    b.HasOne("GLOWAPI.Domain.Entities.Estabelecimento", "Estabelecimento")
                        .WithMany("HorariosProfissionais")
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GLOWAPI.Domain.Entities.Profissional", "Profissional")
                        .WithMany("HorariosAtendimento")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estabelecimento");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.HorarioFuncionamentoEstabelecimento", b =>
                {
                    b.HasOne("GLOWAPI.Domain.Entities.Estabelecimento", "Estabelecimento")
                        .WithMany("HorariosFuncionamento")
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estabelecimento");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.LancamentoCaixa", b =>
                {
                    b.HasOne("GLOWAPI.Domain.Entities.Agendamento", "Agendamento")
                        .WithMany("LancamentosCaixa")
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GLOWAPI.Domain.Entities.Caixa", "Caixa")
                        .WithMany("Lancamentos")
                        .HasForeignKey("CaixaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GLOWAPI.Domain.Entities.Pagamento", "Pagamento")
                        .WithMany("LancamentosCaixa")
                        .HasForeignKey("PagamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GLOWAPI.Domain.Entities.Profissional", "Profissional")
                        .WithMany("LancamentosCaixa")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Agendamento");

                    b.Navigation("Caixa");

                    b.Navigation("Pagamento");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.MetaProfissional", b =>
                {
                    b.HasOne("GLOWAPI.Domain.Entities.ProfissionalEstabelecimento", "ProfissionalEstabelecimento")
                        .WithMany("Metas")
                        .HasForeignKey("ProfissionalEstabelecimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProfissionalEstabelecimento");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("GLOWAPI.Domain.Entities.Agendamento", "Agendamento")
                        .WithMany("Pagamentos")
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GLOWAPI.Domain.Entities.Assinatura", "Assinatura")
                        .WithMany("Pagamentos")
                        .HasForeignKey("AssinaturaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Agendamento");

                    b.Navigation("Assinatura");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Profissional", b =>
                {
                    b.HasOne("GLOWAPI.Domain.Entities.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("GLOWAPI.Domain.Entities.Profissional", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.ProfissionalEstabelecimento", b =>
                {
                    b.HasOne("GLOWAPI.Domain.Entities.Estabelecimento", "Estabelecimento")
                        .WithMany("Profissionais")
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GLOWAPI.Domain.Entities.Profissional", "Profissional")
                        .WithMany("Estabelecimentos")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estabelecimento");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.ProfissionalServico", b =>
                {
                    b.HasOne("GLOWAPI.Domain.Entities.Profissional", "Profissional")
                        .WithMany("Servicos")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GLOWAPI.Domain.Entities.Servico", "Servico")
                        .WithMany("Profissionais")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profissional");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Servico", b =>
                {
                    b.HasOne("GLOWAPI.Domain.Entities.Estabelecimento", "Estabelecimento")
                        .WithMany("Servicos")
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GLOWAPI.Domain.Entities.Profissional", "ProfissionalAutonomo")
                        .WithMany("ServicosAutonomo")
                        .HasForeignKey("ProfissionalAutonomoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Estabelecimento");

                    b.Navigation("ProfissionalAutonomo");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.SessaoAutenticacao", b =>
                {
                    b.HasOne("GLOWAPI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Sessoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Agendamento", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("LancamentosCaixa");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Assinatura", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Caixa", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Estabelecimento", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Assinaturas");

                    b.Navigation("Caixa");

                    b.Navigation("Endereco");

                    b.Navigation("HorariosFuncionamento");

                    b.Navigation("HorariosProfissionais");

                    b.Navigation("Profissionais");

                    b.Navigation("Servicos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Pagamento", b =>
                {
                    b.Navigation("LancamentosCaixa");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Plano", b =>
                {
                    b.Navigation("Assinaturas");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Profissional", b =>
                {
                    b.Navigation("AgendamentoItens");

                    b.Navigation("AgendamentoItensRepassados");

                    b.Navigation("AgendamentosAutonomo");

                    b.Navigation("AssinaturasAutonomo");

                    b.Navigation("Caixa");

                    b.Navigation("Endereco");

                    b.Navigation("Estabelecimentos");

                    b.Navigation("HorariosAtendimento");

                    b.Navigation("LancamentosCaixa");

                    b.Navigation("Servicos");

                    b.Navigation("ServicosAutonomo");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.ProfissionalEstabelecimento", b =>
                {
                    b.Navigation("Comissoes");

                    b.Navigation("Metas");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Servico", b =>
                {
                    b.Navigation("AgendamentoItens");

                    b.Navigation("Profissionais");
                });

            modelBuilder.Entity("GLOWAPI.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Estabelecimentos");

                    b.Navigation("Sessoes");
                });
#pragma warning restore 612, 618
        }
    }
}
